### ISSUE TITLE
Mistake or intentional? 

### ISSUE THREAD

**Issue by dAtiuyy** [YJBeetle/unnpk#20]
unnpk.c:8:10: fatal error: 'magic.h' file not found
Is this a mistake? Did you forget to add a file or is it intentional?

**Comment by tom-snow** [comment]
![image](https://user-images.githubusercontent.com/79245287/195760177-9646348f-b2b1-4339-83e6-e440998d88a4.png)

**Comment by dAtiuyy** [comment]
Checks out. Thanks
