### ISSUE TITLE
FB54F059自身是不是不能被还原成.out？(输出0字节)

### ISSUE THREAD

**Issue by nkzgh** [YJBeetle/unnpk#8]
纯小白一只（甚至不懂Linux和Python），本来想着研究下百鬼修改，一步步靠着谷哥度娘成功跑起来了，想分享下根据fz和楼主两位大佬的步伐的研究成果
通过c32发现script.npk中，从索引表开始（索引表位置记录在0x14处，例如楼主大大的版本入口在00D476C4）第一列 就是偏移量（倒着写的），即解包后的文件名；第二列没分析出来是啥；第三列与第四列重复，即解包后的文件大小（也是倒着写的），但是FB54F059文件 第三列与第三列却不同，第三列是94 04 00 00（1172字节），第四列是60 09 00 00（2400字节）与解包后显示的2.4k吻合。第五列和第六列数据重复（FB54F059不同），第7列均为00 00 00 00（FB54F059为10 00 00 00）。通过c32分析很容易发现FB54F059这个文件与众不同（可能可以通过这个来确定redirect?）
![qq 20181202052535](https://user-images.githubusercontent.com/12379375/49336789-b4b80280-f643-11e8-975a-16d3c68cf1e2.png)
![qq 20181202144108](https://user-images.githubusercontent.com/12379375/49336790-b7b2f300-f643-11e8-88bb-cde5fdc00bb5.png)

**Comment by nkzgh** [comment]
> 的文件大小（也是倒着写的），但是FB54F059文件 第三列与第三列却不同，第三列是94 04 00 00（1172字节），第四列是60 09 00 00（2400字节）与解包后显示的2.4k吻合。第五列和第六列数据重复（FB54F059不同），第7列均为00 00 00 00（FB54F059为10 00 00 00）。通过c32分析很容易发现FB54F059这个文件与众不同（可能可以通过这个来确定redirect?）

**Comment by zhouhang95** [comment]
这是zlib压缩后的文件 最后第七列表示是否被压缩
